### ISSUE TITLE
Imrpove the manage citizen icons in strategic view

### ISSUE THREAD

**Issue by viscoos** [vans163/civ6_qui#3]
Currently when doing manage citizen in strategic view the icon is blocking the resources of the hex. Can you do something about it since you were able to make the bonus, luxury resources smaller. 

thanks

**Comment by znichola** [comment]
It was not me who did the lux resources sizing but I have found a way to modify the manage citizen button and use it in my game. However it is not exclusive strategic view and makes them smaller in the normal view as well. I experimenting with moving the placement of the button putting it more to the the upper right of the hex. But again it messes up the normal view as well. 

Here is an imgur album with icon sizing and offsetting. http://imgur.com/a/Kzcqj

I think it would be possible to make it so they only size in strategic view but I don't know what variable to put in an if statement. 
I also tired using the UI/StrategicView.lua but could not get it working. 

**To sizes the icon** 
UI/WorldView/PlotInfo.lua 
then uncomment this line 
--pInstance.CitizenButton:SetSizeVal(48, 48);
I found using a value of 32 32 works.

**Comment by vans163** [comment]
@viscoos I tried to make it smaller, but then it is all pixelated.  Apparently as zinovic found the value 32,32 works.

@zinovic Nice find, using 48, 48 made the icon all pixelated.  I think the icon needs to be centered as then it looks confusing.  I was thinking about removing the icon all together and simply making the hex being worked light up in 2 different colors, 1 for worked, and 1 for locked.
