### ISSUE TITLE
Linux/Mac has recieved a update

### ISSUE THREAD

**Issue by bulldog98** [vans163/civ6_qui#7]
Linux/Mac has now the Australian Summer update, but workshop version does not work anymore.

**Comment by bulldog98** [comment]
Just saw that the mac/linux version is now deprecated. It would be nice not to have to change the subscription anytime, mac/linux version is behind.

**Comment by chaorace** [comment]
@bulldog98 You've created an issue in the wrong repository, please see the tracker here for future bug reports: https://github.com/chaorace/cqui
